// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.ibs.json.demo.proto.bean;

public final class Request {
  private Request() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Request_PropertiesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string cmd = 1;
    boolean hasCmd();
    String getCmd();
    
    // required int32 key = 7;
    boolean hasKey();
    int getKey();
    
    // optional int32 keycode = 2;
    boolean hasKeycode();
    int getKeycode();
    
    // optional sint32 posX = 3;
    boolean hasPosX();
    int getPosX();
    
    // optional sint32 posY = 4;
    boolean hasPosY();
    int getPosY();
    
    // optional bool onOrOff = 5;
    boolean hasOnOrOff();
    boolean getOnOrOff();
    
    // optional bool ontouch = 6;
    boolean hasOntouch();
    boolean getOntouch();
  }
  public static final class Request_Properties extends
      com.google.protobuf.GeneratedMessage
      implements Request_PropertiesOrBuilder {
    // Use Request_Properties.newBuilder() to construct.
    private Request_Properties(Builder builder) {
      super(builder);
    }
    private Request_Properties(boolean noInit) {}
    
    private static final Request_Properties defaultInstance;
    public static Request_Properties getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request_Properties getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ibs.json.demo.proto.bean.Request.internal_static_com_ibs_json_demo_proto_bean_Request_Properties_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ibs.json.demo.proto.bean.Request.internal_static_com_ibs_json_demo_proto_bean_Request_Properties_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string cmd = 1;
    public static final int CMD_FIELD_NUMBER = 1;
    private java.lang.Object cmd_;
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          cmd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 key = 7;
    public static final int KEY_FIELD_NUMBER = 7;
    private int key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getKey() {
      return key_;
    }
    
    // optional int32 keycode = 2;
    public static final int KEYCODE_FIELD_NUMBER = 2;
    private int keycode_;
    public boolean hasKeycode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getKeycode() {
      return keycode_;
    }
    
    // optional sint32 posX = 3;
    public static final int POSX_FIELD_NUMBER = 3;
    private int posX_;
    public boolean hasPosX() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getPosX() {
      return posX_;
    }
    
    // optional sint32 posY = 4;
    public static final int POSY_FIELD_NUMBER = 4;
    private int posY_;
    public boolean hasPosY() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getPosY() {
      return posY_;
    }
    
    // optional bool onOrOff = 5;
    public static final int ONOROFF_FIELD_NUMBER = 5;
    private boolean onOrOff_;
    public boolean hasOnOrOff() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public boolean getOnOrOff() {
      return onOrOff_;
    }
    
    // optional bool ontouch = 6;
    public static final int ONTOUCH_FIELD_NUMBER = 6;
    private boolean ontouch_;
    public boolean hasOntouch() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public boolean getOntouch() {
      return ontouch_;
    }
    
    private void initFields() {
      cmd_ = "";
      key_ = 0;
      keycode_ = 0;
      posX_ = 0;
      posY_ = 0;
      onOrOff_ = false;
      ontouch_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCmdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(2, keycode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeSInt32(3, posX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeSInt32(4, posY_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(5, onOrOff_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(6, ontouch_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(7, key_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCmdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, keycode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, posX_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, posY_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, onOrOff_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, ontouch_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, key_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.ibs.json.demo.proto.bean.Request.Request_Properties parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ibs.json.demo.proto.bean.Request.Request_Properties parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ibs.json.demo.proto.bean.Request.Request_Properties parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.ibs.json.demo.proto.bean.Request.Request_Properties parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.ibs.json.demo.proto.bean.Request.Request_Properties parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ibs.json.demo.proto.bean.Request.Request_Properties parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.ibs.json.demo.proto.bean.Request.Request_Properties parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ibs.json.demo.proto.bean.Request.Request_Properties parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.ibs.json.demo.proto.bean.Request.Request_Properties parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.ibs.json.demo.proto.bean.Request.Request_Properties parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ibs.json.demo.proto.bean.Request.Request_Properties prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ibs.json.demo.proto.bean.Request.Request_PropertiesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ibs.json.demo.proto.bean.Request.internal_static_com_ibs_json_demo_proto_bean_Request_Properties_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ibs.json.demo.proto.bean.Request.internal_static_com_ibs_json_demo_proto_bean_Request_Properties_fieldAccessorTable;
      }
      
      // Construct using com.ibs.json.demo.proto.bean.Request.Request_Properties.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        cmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        keycode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        posX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        posY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        onOrOff_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        ontouch_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ibs.json.demo.proto.bean.Request.Request_Properties.getDescriptor();
      }
      
      public com.ibs.json.demo.proto.bean.Request.Request_Properties getDefaultInstanceForType() {
        return com.ibs.json.demo.proto.bean.Request.Request_Properties.getDefaultInstance();
      }
      
      public com.ibs.json.demo.proto.bean.Request.Request_Properties build() {
        com.ibs.json.demo.proto.bean.Request.Request_Properties result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.ibs.json.demo.proto.bean.Request.Request_Properties buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.ibs.json.demo.proto.bean.Request.Request_Properties result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.ibs.json.demo.proto.bean.Request.Request_Properties buildPartial() {
        com.ibs.json.demo.proto.bean.Request.Request_Properties result = new com.ibs.json.demo.proto.bean.Request.Request_Properties(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.keycode_ = keycode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.posX_ = posX_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.posY_ = posY_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.onOrOff_ = onOrOff_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ontouch_ = ontouch_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ibs.json.demo.proto.bean.Request.Request_Properties) {
          return mergeFrom((com.ibs.json.demo.proto.bean.Request.Request_Properties)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.ibs.json.demo.proto.bean.Request.Request_Properties other) {
        if (other == com.ibs.json.demo.proto.bean.Request.Request_Properties.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasKeycode()) {
          setKeycode(other.getKeycode());
        }
        if (other.hasPosX()) {
          setPosX(other.getPosX());
        }
        if (other.hasPosY()) {
          setPosY(other.getPosY());
        }
        if (other.hasOnOrOff()) {
          setOnOrOff(other.getOnOrOff());
        }
        if (other.hasOntouch()) {
          setOntouch(other.getOntouch());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCmd()) {
          
          return false;
        }
        if (!hasKey()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              cmd_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000004;
              keycode_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000008;
              posX_ = input.readSInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000010;
              posY_ = input.readSInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000020;
              onOrOff_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000040;
              ontouch_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000002;
              key_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string cmd = 1;
      private java.lang.Object cmd_ = "";
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCmd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      void setCmd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
      }
      
      // required int32 key = 7;
      private int key_ ;
      public boolean hasKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getKey() {
        return key_;
      }
      public Builder setKey(int value) {
        bitField0_ |= 0x00000002;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 keycode = 2;
      private int keycode_ ;
      public boolean hasKeycode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getKeycode() {
        return keycode_;
      }
      public Builder setKeycode(int value) {
        bitField0_ |= 0x00000004;
        keycode_ = value;
        onChanged();
        return this;
      }
      public Builder clearKeycode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        keycode_ = 0;
        onChanged();
        return this;
      }
      
      // optional sint32 posX = 3;
      private int posX_ ;
      public boolean hasPosX() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getPosX() {
        return posX_;
      }
      public Builder setPosX(int value) {
        bitField0_ |= 0x00000008;
        posX_ = value;
        onChanged();
        return this;
      }
      public Builder clearPosX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        posX_ = 0;
        onChanged();
        return this;
      }
      
      // optional sint32 posY = 4;
      private int posY_ ;
      public boolean hasPosY() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getPosY() {
        return posY_;
      }
      public Builder setPosY(int value) {
        bitField0_ |= 0x00000010;
        posY_ = value;
        onChanged();
        return this;
      }
      public Builder clearPosY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        posY_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool onOrOff = 5;
      private boolean onOrOff_ ;
      public boolean hasOnOrOff() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getOnOrOff() {
        return onOrOff_;
      }
      public Builder setOnOrOff(boolean value) {
        bitField0_ |= 0x00000020;
        onOrOff_ = value;
        onChanged();
        return this;
      }
      public Builder clearOnOrOff() {
        bitField0_ = (bitField0_ & ~0x00000020);
        onOrOff_ = false;
        onChanged();
        return this;
      }
      
      // optional bool ontouch = 6;
      private boolean ontouch_ ;
      public boolean hasOntouch() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public boolean getOntouch() {
        return ontouch_;
      }
      public Builder setOntouch(boolean value) {
        bitField0_ |= 0x00000040;
        ontouch_ = value;
        onChanged();
        return this;
      }
      public Builder clearOntouch() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ontouch_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ibs.json.demo.proto.bean.Request_Properties)
    }
    
    static {
      defaultInstance = new Request_Properties(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ibs.json.demo.proto.bean.Request_Properties)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ibs_json_demo_proto_bean_Request_Properties_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ibs_json_demo_proto_bean_Request_Properties_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\022\034com.ibs.json.demo.proto" +
      ".bean\"}\n\022Request_Properties\022\013\n\003cmd\030\001 \002(\t" +
      "\022\013\n\003key\030\007 \002(\005\022\017\n\007keycode\030\002 \001(\005\022\014\n\004posX\030\003" +
      " \001(\021\022\014\n\004posY\030\004 \001(\021\022\017\n\007onOrOff\030\005 \001(\010\022\017\n\007o" +
      "ntouch\030\006 \001(\010B\'\n\034com.ibs.json.demo.proto." +
      "beanB\007Request"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ibs_json_demo_proto_bean_Request_Properties_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ibs_json_demo_proto_bean_Request_Properties_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ibs_json_demo_proto_bean_Request_Properties_descriptor,
              new java.lang.String[] { "Cmd", "Key", "Keycode", "PosX", "PosY", "OnOrOff", "Ontouch", },
              com.ibs.json.demo.proto.bean.Request.Request_Properties.class,
              com.ibs.json.demo.proto.bean.Request.Request_Properties.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
